# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models


#Migrations are Django’s way of propagating changes you make to your models (adding a field, deleting a model, etc.) into your database schema.
#do this whenever you change models; changes database live
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
