# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_answer_iscorrect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banana', models.CharField(max_length=10)),
            ],
        ),
    ]
