# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_banana'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banana',
        ),
    ]
